# Generated by Django 3.0.3 on 2020-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='nimi',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.AddField(
            model_name='book',
            name='tiedot',
            field=models.TextField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
